import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My blog, guys",
  description: "Generated by Helio's Coolness",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="max-w-5xl mx-auto px-4 py-5">
            <Navbar />
             {children}
            </main>
            
          </ThemeProvider>
        <div className="bg-slate-100 py-16 dark:bg-slate-700 ">
          <Footer />
        </div>
        
      </body>
    </html>
  );
}
